#!/usr/bin/env bash

red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)
reset=$(tput sgr0)

# Catch leftover print statemments minus our logging class, which uses print to log
export BLOCKER=0
echo "${yellow}Looking for lingering comment blocks${reset}"
printf "%10s" "${yellow}Checking print: ${reset}"
if grep -r -q --include="*.lua" --exclude="flight_maint.lua" "print"; then
  printf "%10s\n" "${red}FAIL${reset}"
  grep -r --include="*.lua" --exclude="flight_maint.lua" -n "print"
  BLOCKER=1
else
  printf "%10s\n" "${green}OK${reset}"
fi

for keyword in TODO FIXME FIX BUG; do
  printf "%10s" "${yellow}Checking ${keyword}: ${reset}"
  if grep -r -q --include="*.lua" -i "${keyword}:"; then
    printf "%10s\n" "${red}FAIL${reset}"
    grep -r --include="*.lua" -n "${keyword}:"
    BLOCKER=1
  else
    printf "%10s\n" "${green}OK${reset}"
  fi
done

if [ "${BLOCKER}" == 1 ]; then
  exit 1
fi
echo ""

# # Confirm basic tests pass

echo "${yellow}Running luacheck${reset}"
if ! luacheck .; then
  printf "%10s\n" "${red}luacheck failed. Commit aborted.${reset}"
  exit 1
fi
