#!/usr/bin/env bash

red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)
reset=$(tput sgr0)

# Catch TODO comments
export BLOCKER=0
for keyword in print TODO FIXME FIX BUG; do
  if git grep --cached -r -q "${keyword}:" -- "*.lua"; then
    printf "%10s\n" "${red}${keyword}${reset} ${yellow}found in your comments. Resolve before pushing.${reset}"
    grep -r --include="*.lua" -n "${keyword}:"
    echo ""
    BLOCKER=1
  fi
done

if [ "${BLOCKER}" == 1 ]; then
  exit 1
fi

# # Confirm basic tests pass

if ! luacheck .; then
  printf "%10s\n" "${red}luacheck failed. Commit aborted.${reset}"
  exit 1
fi
